package com.jmeter.plugin.docx.reporter;

import com.jmeter.plugin.docx.util.HtmlToImageRenderer;
import com.jmeter.plugin.docx.util.SampleVariableResolver;
import com.jmeter.plugin.docx.util.SummaryStatistics;
import org.apache.jmeter.samplers.SampleResult;
import org.apache.poi.util.Units;
import org.apache.poi.xwpf.model.XWPFHeaderFooterPolicy;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableCell;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTBorder;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTSectPr;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTTblBorders;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTTblPr;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.STBorder;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.STHdrFtr;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * Generates DOCX reports from JMeter sample results.
 */
public class DocxReportGenerator {

    private static final Logger log = LoggerFactory.getLogger(DocxReportGenerator.class);
    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    public static final String MODE_TABLE = "Table";
    public static final String MODE_PARAGRAPH = "Paragraph";

    private String documentTitle;
    private String pageHeader;
    private String recordHeader;
    private String recordFormat;
    private String footerSection;
    private String displayMode;
    private boolean includeSummary;
    private boolean renderHtmlAsImage;

    // Image rendering settings for table cells
    private static final int HTML_IMAGE_WIDTH = 1280;  // Render width in pixels (desktop mode)
    private static final int TABLE_IMAGE_WIDTH_EMU = Units.toEMU(200);  // 200 points width in table cell
    private static final int TABLE_IMAGE_MAX_HEIGHT_EMU = Units.toEMU(150);  // 150 points max height

    public DocxReportGenerator() {
        this.documentTitle = "Performance Test Report";
        this.pageHeader = "";
        this.recordHeader = "Sample Label | Response Time | Status";
        this.recordFormat = "%sampleLabel% | %responseTime% | %isSuccessful%";
        this.footerSection = "Generated by JMeter Advanced DOCX Reporter";
        this.displayMode = MODE_TABLE;
        this.includeSummary = true;
        this.renderHtmlAsImage = false;
    }

    /**
     * Generates the DOCX report file.
     *
     * @param filename   The output file path
     * @param statistics The summary statistics containing all samples
     * @throws IOException If file writing fails
     */
    public void generateReport(String filename, SummaryStatistics statistics) throws IOException {
        try (XWPFDocument document = new XWPFDocument()) {
            // Add page header
            if (pageHeader != null && !pageHeader.isEmpty()) {
                addPageHeader(document, pageHeader);
            }

            // Add document title
            addTitle(document, documentTitle);

            // Add samples based on display mode
            List<SampleResult> samples = statistics.getSamples();
            if (!samples.isEmpty()) {
                if (MODE_TABLE.equals(displayMode)) {
                    addSamplesAsTable(document, samples);
                } else {
                    addSamplesAsParagraphs(document, samples);
                }
            }

            // Add summary statistics
            if (includeSummary) {
                addSummarySection(document, statistics);
            }

            // Add footer section
            if (footerSection != null && !footerSection.isEmpty()) {
                addFooterSection(document, footerSection);
            }

            // Write to file
            try (FileOutputStream out = new FileOutputStream(filename)) {
                document.write(out);
            }

            log.info("DOCX report generated: {}", filename);
        }
    }

    /**
     * Adds a page header to the document.
     */
    private void addPageHeader(XWPFDocument document, String headerText) {
        try {
            CTSectPr sectPr = document.getDocument().getBody().addNewSectPr();
            XWPFHeaderFooterPolicy policy = new XWPFHeaderFooterPolicy(document, sectPr);

            // Create header paragraph
            XWPFParagraph headerPara = new XWPFParagraph(
                    org.openxmlformats.schemas.wordprocessingml.x2006.main.CTP.Factory.newInstance(),
                    document);
            headerPara.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun run = headerPara.createRun();
            run.setText(headerText);
            run.setFontSize(10);
            run.setColor("666666");

            policy.createHeader(STHdrFtr.DEFAULT, new XWPFParagraph[]{headerPara});
        } catch (Exception e) {
            log.warn("Could not create page header: {}", e.getMessage());
        }
    }

    /**
     * Adds the document title as a heading.
     */
    private void addTitle(XWPFDocument document, String title) {
        XWPFParagraph titleParagraph = document.createParagraph();
        titleParagraph.setAlignment(ParagraphAlignment.CENTER);
        titleParagraph.setSpacingAfter(400);

        XWPFRun titleRun = titleParagraph.createRun();
        titleRun.setText(title);
        titleRun.setBold(true);
        titleRun.setFontSize(24);
        titleRun.setFontFamily("Arial");

        // Add generation timestamp
        XWPFParagraph dateParagraph = document.createParagraph();
        dateParagraph.setAlignment(ParagraphAlignment.CENTER);
        dateParagraph.setSpacingAfter(600);

        XWPFRun dateRun = dateParagraph.createRun();
        dateRun.setText("Generated on: " + DATE_FORMAT.format(new Date()));
        dateRun.setFontSize(10);
        dateRun.setItalic(true);
        dateRun.setColor("666666");
    }

    /**
     * Adds samples as a table.
     */
    private void addSamplesAsTable(XWPFDocument document, List<SampleResult> samples) {
        // Add section header
        XWPFParagraph sectionHeader = document.createParagraph();
        sectionHeader.setSpacingBefore(400);
        XWPFRun sectionRun = sectionHeader.createRun();
        sectionRun.setText("Test Results");
        sectionRun.setBold(true);
        sectionRun.setFontSize(16);

        // Parse column headers
        String[] headers = recordHeader.split("\\|");
        int columnCount = headers.length;

        // Parse column format templates (split by | but preserve the variable placeholders)
        String[] columnTemplates = recordFormat.split("\\|");

        // Create table
        XWPFTable table = document.createTable(1, columnCount);
        table.setWidth("100%");

        // Style the table
        CTTblPr tblPr = table.getCTTbl().getTblPr();
        if (tblPr == null) {
            tblPr = table.getCTTbl().addNewTblPr();
        }
        CTTblBorders borders = tblPr.addNewTblBorders();
        setBorder(borders.addNewTop());
        setBorder(borders.addNewBottom());
        setBorder(borders.addNewLeft());
        setBorder(borders.addNewRight());
        setBorder(borders.addNewInsideH());
        setBorder(borders.addNewInsideV());

        // Add header row
        XWPFTableRow headerRow = table.getRow(0);
        for (int i = 0; i < columnCount; i++) {
            XWPFTableCell cell = headerRow.getCell(i);
            cell.setColor("4472C4");
            XWPFParagraph para = cell.getParagraphs().get(0);
            para.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun run = para.createRun();
            run.setText(headers[i].trim());
            run.setBold(true);
            run.setColor("FFFFFF");
            run.setFontSize(10);
        }

        // Find which column contains responseData (for image embedding)
        int responseDataColumnIndex = -1;
        for (int i = 0; i < columnTemplates.length; i++) {
            if (columnTemplates[i].contains("%responseData%")) {
                responseDataColumnIndex = i;
                break;
            }
        }

        // Add data rows
        for (int rowIndex = 0; rowIndex < samples.size(); rowIndex++) {
            SampleResult sample = samples.get(rowIndex);

            // Resolve each column template separately to avoid delimiter conflicts
            List<String> values = resolveColumnValues(sample, columnTemplates, renderHtmlAsImage);

            // Check if this sample has HTML response that should be rendered as image
            String responseData = sample.getResponseDataAsString();
            boolean shouldRenderAsImage = renderHtmlAsImage && HtmlToImageRenderer.isHtml(responseData);

            XWPFTableRow row = table.createRow();

            // Alternate row colors
            String bgColor = (rowIndex % 2 == 0) ? "F2F2F2" : "FFFFFF";

            for (int i = 0; i < columnCount; i++) {
                XWPFTableCell cell = row.getCell(i);
                if (cell == null) {
                    cell = row.addNewTableCell();
                }
                cell.setColor(bgColor);

                XWPFParagraph para = cell.getParagraphs().get(0);

                // If this is the responseData column and we should render as image
                if (i == responseDataColumnIndex && shouldRenderAsImage) {
                    // Render HTML to image and embed in cell
                    try {
                        byte[] imageBytes = HtmlToImageRenderer.renderHtmlToImage(responseData, HTML_IMAGE_WIDTH);
                        if (imageBytes != null) {
                            // Calculate image dimensions to fit in table cell
                            ByteArrayInputStream bis = new ByteArrayInputStream(imageBytes);
                            BufferedImage bufferedImage = ImageIO.read(bis);
                            bis.close();

                            int imgWidth = bufferedImage.getWidth();
                            int imgHeight = bufferedImage.getHeight();

                            // Scale to fit within table cell constraints
                            int widthEmu = TABLE_IMAGE_WIDTH_EMU;
                            int heightEmu = (int) ((double) imgHeight / imgWidth * widthEmu);

                            // Limit height if too tall
                            if (heightEmu > TABLE_IMAGE_MAX_HEIGHT_EMU) {
                                heightEmu = TABLE_IMAGE_MAX_HEIGHT_EMU;
                                widthEmu = (int) ((double) imgWidth / imgHeight * heightEmu);
                            }

                            // Add image to cell
                            XWPFRun imageRun = para.createRun();
                            bis = new ByteArrayInputStream(imageBytes);
                            imageRun.addPicture(bis, XWPFDocument.PICTURE_TYPE_PNG,
                                    "response_" + (rowIndex + 1) + ".png", widthEmu, heightEmu);
                            bis.close();
                        } else {
                            // Fallback to text if image rendering fails
                            XWPFRun run = para.createRun();
                            run.setText("[Image rendering failed]");
                            run.setFontSize(9);
                            run.setColor("999999");
                        }
                    } catch (Exception e) {
                        log.warn("Failed to embed HTML image for sample {}: {}",
                                sample.getSampleLabel(), e.getMessage());
                        XWPFRun run = para.createRun();
                        run.setText("[Image error]");
                        run.setFontSize(9);
                        run.setColor("999999");
                    }
                } else {
                    // Regular text cell
                    XWPFRun run = para.createRun();
                    String value = (i < values.size()) ? values.get(i).trim() : "";

                    run.setText(value);
                    run.setFontSize(9);

                    // Color code success/failure
                    if (value.equalsIgnoreCase("true")) {
                        run.setColor("228B22");
                    } else if (value.equalsIgnoreCase("false")) {
                        run.setColor("DC143C");
                    }
                }
            }
        }
    }

    /**
     * Resolves each column template separately using the SampleResult variables.
     * This avoids issues where the resolved value contains the delimiter character.
     * When renderHtmlAsImage is true, HTML responseData column is left empty (image embedded separately).
     */
    private List<String> resolveColumnValues(SampleResult sample, String[] columnTemplates, boolean renderHtmlAsImage) {
        List<String> values = new ArrayList<>();
        Map<String, String> variables = SampleVariableResolver.extractVariables(sample);

        // Check if responseData is HTML and should be rendered as image
        String responseData = sample.getResponseDataAsString();
        boolean isHtmlResponse = renderHtmlAsImage && HtmlToImageRenderer.isHtml(responseData);

        for (String template : columnTemplates) {
            String resolved = template.trim();

            // If this template contains responseData and it's HTML, leave empty (image will be embedded)
            if (isHtmlResponse && template.contains("%responseData%")) {
                resolved = resolved.replace("%responseData%", "");
            }

            // Replace all other variables
            for (Map.Entry<String, String> entry : variables.entrySet()) {
                // Skip responseData if already handled above
                if (isHtmlResponse && "responseData".equals(entry.getKey())) {
                    continue;
                }
                resolved = resolved.replace("%" + entry.getKey() + "%", entry.getValue());
            }
            values.add(resolved);
        }

        return values;
    }

    /**
     * Adds samples as paragraphs.
     */
    private void addSamplesAsParagraphs(XWPFDocument document, List<SampleResult> samples) {
        // Add section header
        XWPFParagraph sectionHeader = document.createParagraph();
        sectionHeader.setSpacingBefore(400);
        XWPFRun sectionRun = sectionHeader.createRun();
        sectionRun.setText("Test Results");
        sectionRun.setBold(true);
        sectionRun.setFontSize(16);

        for (int i = 0; i < samples.size(); i++) {
            SampleResult sample = samples.get(i);
            String responseData = sample.getResponseDataAsString();
            boolean shouldRenderAsImage = renderHtmlAsImage && HtmlToImageRenderer.isHtml(responseData);

            // For HTML rendering, replace responseData placeholder with empty string
            // (we'll add the image separately)
            String resolvedFormat;
            if (shouldRenderAsImage) {
                String originalResponseData = responseData != null ? responseData : "";
                resolvedFormat = SampleVariableResolver.resolve(recordFormat, sample)
                        .replace(originalResponseData, "[See image below]");
            } else {
                resolvedFormat = SampleVariableResolver.resolve(recordFormat, sample);
            }

            XWPFParagraph para = document.createParagraph();
            para.setSpacingBefore(100);
            para.setSpacingAfter(100);

            // Add sample number
            XWPFRun numberRun = para.createRun();
            numberRun.setText("Sample " + (i + 1) + ": ");
            numberRun.setBold(true);
            numberRun.setFontSize(10);

            // Add sample data with newline support
            XWPFRun dataRun = para.createRun();
            String[] lines = resolvedFormat.split("\\\\n|\\n");
            for (int j = 0; j < lines.length; j++) {
                dataRun.setText(lines[j]);
                if (j < lines.length - 1) {
                    dataRun.addBreak();
                }
            }
            dataRun.setFontSize(10);

            // Color based on success/failure
            if (sample.isSuccessful()) {
                dataRun.setColor("228B22");
            } else {
                dataRun.setColor("DC143C");
            }

            // Render HTML response as image if enabled
            if (shouldRenderAsImage) {
                try {
                    byte[] imageBytes = HtmlToImageRenderer.renderHtmlToImage(responseData, HTML_IMAGE_WIDTH);
                    if (imageBytes != null) {
                        // Create a new paragraph for the image
                        XWPFParagraph imagePara = document.createParagraph();
                        imagePara.setSpacingBefore(100);
                        imagePara.setSpacingAfter(200);

                        // Calculate image dimensions
                        ByteArrayInputStream bis = new ByteArrayInputStream(imageBytes);
                        BufferedImage bufferedImage = ImageIO.read(bis);
                        bis.close();

                        int imgWidth = bufferedImage.getWidth();
                        int imgHeight = bufferedImage.getHeight();

                        // Scale to fit page width (about 6 inches = 432 points)
                        int maxWidthEmu = Units.toEMU(432);
                        int widthEmu = maxWidthEmu;
                        int heightEmu = (int) ((double) imgHeight / imgWidth * widthEmu);

                        // Add image
                        XWPFRun imageRun = imagePara.createRun();
                        bis = new ByteArrayInputStream(imageBytes);
                        imageRun.addPicture(bis, XWPFDocument.PICTURE_TYPE_PNG,
                                "response_" + (i + 1) + ".png", widthEmu, heightEmu);
                        bis.close();
                    }
                } catch (Exception e) {
                    log.warn("Failed to render HTML image for sample {}: {}",
                            sample.getSampleLabel(), e.getMessage());
                    // Add error message paragraph
                    XWPFParagraph errorPara = document.createParagraph();
                    XWPFRun errorRun = errorPara.createRun();
                    errorRun.setText("[Image rendering failed]");
                    errorRun.setFontSize(9);
                    errorRun.setItalic(true);
                    errorRun.setColor("999999");
                }
            }
        }
    }

    /**
     * Adds the summary statistics section.
     */
    private void addSummarySection(XWPFDocument document, SummaryStatistics statistics) {
        // Add section header
        XWPFParagraph sectionHeader = document.createParagraph();
        sectionHeader.setSpacingBefore(600);
        XWPFRun sectionRun = sectionHeader.createRun();
        sectionRun.setText("Summary Statistics");
        sectionRun.setBold(true);
        sectionRun.setFontSize(16);

        // Create summary table
        XWPFTable table = document.createTable(6, 2);
        table.setWidth("50%");

        // Style the table
        CTTblPr tblPr = table.getCTTbl().getTblPr();
        if (tblPr == null) {
            tblPr = table.getCTTbl().addNewTblPr();
        }
        CTTblBorders borders = tblPr.addNewTblBorders();
        setBorder(borders.addNewTop());
        setBorder(borders.addNewBottom());
        setBorder(borders.addNewLeft());
        setBorder(borders.addNewRight());
        setBorder(borders.addNewInsideH());
        setBorder(borders.addNewInsideV());

        // Add statistics rows
        addSummaryRow(table.getRow(0), "Total Samples", String.valueOf(statistics.getTotalSamples()));
        addSummaryRow(table.getRow(1), "Average Response Time", String.format("%.2f ms", statistics.getAverageResponseTime()));
        addSummaryRow(table.getRow(2), "Min Response Time", statistics.getMinResponseTime() + " ms");
        addSummaryRow(table.getRow(3), "Max Response Time", statistics.getMaxResponseTime() + " ms");
        addSummaryRow(table.getRow(4), "Error Count / Rate", String.format("%d (%.2f%%)", statistics.getTotalErrors(), statistics.getErrorRate()));
        addSummaryRow(table.getRow(5), "Throughput", String.format("%.2f req/sec", statistics.getThroughput()));
    }

    /**
     * Helper method to add a summary row.
     */
    private void addSummaryRow(XWPFTableRow row, String label, String value) {
        XWPFTableCell labelCell = row.getCell(0);
        labelCell.setColor("E7E6E6");
        XWPFParagraph labelPara = labelCell.getParagraphs().get(0);
        XWPFRun labelRun = labelPara.createRun();
        labelRun.setText(label);
        labelRun.setBold(true);
        labelRun.setFontSize(10);

        XWPFTableCell valueCell = row.getCell(1);
        XWPFParagraph valuePara = valueCell.getParagraphs().get(0);
        XWPFRun valueRun = valuePara.createRun();
        valueRun.setText(value);
        valueRun.setFontSize(10);
    }

    /**
     * Sets border style for table borders.
     */
    private void setBorder(CTBorder border) {
        border.setVal(STBorder.SINGLE);
        border.setSz(BigInteger.valueOf(4));
        border.setColor("CCCCCC");
    }

    /**
     * Adds the footer section at the end of the document.
     */
    private void addFooterSection(XWPFDocument document, String footer) {
        XWPFParagraph footerParagraph = document.createParagraph();
        footerParagraph.setSpacingBefore(600);
        footerParagraph.setAlignment(ParagraphAlignment.CENTER);

        // Add horizontal line
        XWPFRun lineRun = footerParagraph.createRun();
        lineRun.setText("─".repeat(50));
        lineRun.setColor("CCCCCC");
        lineRun.addBreak();
        lineRun.addBreak();

        XWPFRun footerRun = footerParagraph.createRun();
        footerRun.setText(footer);
        footerRun.setFontSize(10);
        footerRun.setItalic(true);
        footerRun.setColor("666666");
    }

    // Getters and Setters

    public String getDocumentTitle() {
        return documentTitle;
    }

    public void setDocumentTitle(String documentTitle) {
        this.documentTitle = documentTitle;
    }

    public String getPageHeader() {
        return pageHeader;
    }

    public void setPageHeader(String pageHeader) {
        this.pageHeader = pageHeader;
    }

    public String getRecordHeader() {
        return recordHeader;
    }

    public void setRecordHeader(String recordHeader) {
        this.recordHeader = recordHeader;
    }

    public String getRecordFormat() {
        return recordFormat;
    }

    public void setRecordFormat(String recordFormat) {
        this.recordFormat = recordFormat;
    }

    public String getFooterSection() {
        return footerSection;
    }

    public void setFooterSection(String footerSection) {
        this.footerSection = footerSection;
    }

    public String getDisplayMode() {
        return displayMode;
    }

    public void setDisplayMode(String displayMode) {
        this.displayMode = displayMode;
    }

    public boolean isIncludeSummary() {
        return includeSummary;
    }

    public void setIncludeSummary(boolean includeSummary) {
        this.includeSummary = includeSummary;
    }

    public boolean isRenderHtmlAsImage() {
        return renderHtmlAsImage;
    }

    public void setRenderHtmlAsImage(boolean renderHtmlAsImage) {
        this.renderHtmlAsImage = renderHtmlAsImage;
    }
}
